Shop-Inventory:
  Trade-Material: 141 # here material trade id
  ArmorII:
    cost: 25
  ArmorIII:
    cost: 22
  ArmorIV:
    cost: 111
    
    
    
    
#B3rf ene 6walt 3leek mra bs mreet bkm 9'rf weeeee kman ma6alt shwayt we ana a38ed al ashi2a we 8lt lazm aswe w adeef we a5r she ma 3mlt she :)